#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Install hooks: npx husky install
# Install commitlint: npm -g install commitlint @commitlint/config-conventional

commitlint --config .husky/commitlint.config.js --extends $(npm root -g)/@commitlint/config-conventional --from origin/main
